version: 0.1

phases:
  pre_build:
    commands:
      - echo maven clean on `date`
      - mvn clean  
  build:
    commands:
      - echo maven package on `date`
      - mvn package

artifacts:
  files:
    - '**/*'
  base-directory: 'target/ROOT'
